In [3]:
import numpy as np

In [4]:
num = 789
arr = np.array(num)
print(num)
print(arr)
print(type(num))
print(type(arr))
print(arr.dtype)
print(arr.itemsize)
print(arr.ndim)
print(arr.size)
print(arr.shape)

789
789
<class 'int'>
<class 'numpy.ndarray'>
int32
4
0
1
()


In [5]:
array = np.array([1, 2, 3.5, 6, 7, 8, 9])
print(array)
array = np.array([1, 2, 3.5, 6, 7, 8, 9], dtype=str)
print(array)
print(type(array))
print(len(array))
print(list(array))
print(tuple(array))
print(array[1::2])

[1.  2.  3.5 6.  7.  8.  9. ]
['1' '2' '3.5' '6' '7' '8' '9']
<class 'numpy.ndarray'>
7
['1', '2', '3.5', '6', '7', '8', '9']
('1', '2', '3.5', '6', '7', '8', '9')
['2' '6' '8']


In [6]:
lst = [1, 2, 3.5, 6, 7, 8, 9]
lst[1:4] = [99, 22]
print(lst)
# array[1:4] = [99, 22]
array[1:4] = [99, 22, 44]
print(array)

[1, 99, 22, 7, 8, 9]
['1' '99' '22' '44' '7' '8' '9']


In [7]:
arr = np.array(lst, dtype=np.int8)
print(lst)
print(arr)
print(arr.dtype)
print(arr.itemsize)
print(arr.ndim)
print(arr.size)
print(arr.shape)

[1, 99, 22, 7, 8, 9]
[ 1 99 22  7  8  9]
int8
1
1
6
(6,)


In [8]:
arr = np.array(lst, dtype=int)
print(arr.dtype)
print(arr.itemsize)
print(arr.ndim)
print(arr.size)
print(arr.shape)

int32
4
1
6
(6,)


In [9]:
arr = np.array({'name': 'jake', 'age': 23})
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.itemsize)
print(arr.ndim)
print(arr.size)
print(arr.shape)

{'name': 'jake', 'age': 23}
<class 'numpy.ndarray'>
object
8
0
1
()


In [10]:
# lst = [[8, 9, 2], [3, 7]]
lst = [[8, 9, 2], [3, 7.2, 6]]
arr = np.array(lst)
print(lst)
print(arr)
print(len(lst))
print(len(arr))
print(arr.size)
print(arr.shape)

[[8, 9, 2], [3, 7.2, 6]]
[[8.  9.  2. ]
 [3.  7.2 6. ]]
2
2
6
(2, 3)


In [11]:
lst = [[[8, 9], [2, 3], [3, 7], [6, 8]]]
arr = np.array(lst)
print(arr)
print(arr.shape)

[[[8 9]
  [2 3]
  [3 7]
  [6 8]]]
(1, 4, 2)


In [12]:
lst = [[[[8, 9, 6], [2, 3, 0]], [[7, 6, 7], [4, 1, 3]]]]
arr = np.array(lst)
print(arr)
print(arr.shape)

[[[[8 9 6]
   [2 3 0]]

  [[7 6 7]
   [4 1 3]]]]
(1, 2, 2, 3)


In [13]:
lst = [[[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]], [[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]]]
arr = np.array(lst)
print(arr.shape)

(2, 1, 4, 3)


In [14]:
print(list(range(1, 10, 2)))
print(np.arange(1, 10, 2))

[1, 3, 5, 7, 9]
[1 3 5 7 9]


In [15]:
print(list(range(9, 0, -2)))
print(np.arange(9, 0, -2))

[9, 7, 5, 3, 1]
[9 7 5 3 1]


In [16]:
print(list(range(1, 6)))
print(np.arange(1, 6))
print(list(range(6)))
print(np.arange(6))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [17]:
# print(list(range(1.5, 12, 2.5)))
print(np.arange(1.5, 12, 2.5))

[ 1.5  4.   6.5  9.  11.5]


In [18]:
print(np.linspace(1, 50))
print(np.linspace(1, 10, num=10))
print(np.linspace(1, 10, num=10, dtype=np.int32))
print(np.linspace(1, 10, num=10, dtype=int))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
print(np.linspace(1, 50, num=25))
print(np.linspace(1, 50, num=25, dtype=int))

[ 1.          3.04166667  5.08333333  7.125       9.16666667 11.20833333
 13.25       15.29166667 17.33333333 19.375      21.41666667 23.45833333
 25.5        27.54166667 29.58333333 31.625      33.66666667 35.70833333
 37.75       39.79166667 41.83333333 43.875      45.91666667 47.95833333
 50.        ]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 50]


In [20]:
arr = np.arange(24)
print(arr.reshape(4, 6))
print('*' * 30)
print(np.reshape(arr, (4, 6)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
******************************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [21]:
print(np.reshape(arr, (4, 2, 3)))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [24]:
arr = np.arange(24)
print(np.reshape(arr, (4, -1)))
print(np.reshape(arr, (5, -1)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [25]:
arr = np.arange(24).reshape(4, 6)
print(np.reshape(arr, (24,)))
print(np.reshape(arr, 24))
print(np.reshape(arr, -1))
print(arr.reshape(24))
print(arr.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [26]:
arr = np.arange(24).reshape(4, 6)
print(arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
