#### NumPy（Numerical Python）是 Python 进行科学计算的一个扩展库，提供了大量的函数和操作，主要用于对多维数组执行计算，它比 Python 自身的嵌套列表结构要高效的多。 
- 多维性，同质性 

#### NumPy 数组和 Python 列表的主要区别：  
- 数组会对元素的数据类型做统一，而列表不会。  
- 数组创建后具有固定大小，而列表由于内存自动管理，可动态调整。

In [1]:
import numpy as np

#### np.array(object, dtype=None)
创建数组:  
- object：array_like，类似于数组的对象。如果object是标量，则返回包含object的0维数组  
- dtype：data-type，数据类型。如果没有给出，会从输入数据推断数据类型  
- 创建一个数组对象并返回（ndarray实例对象）

|DTYPE常用值| 描述              |
|--|-----------------|
|np.int8 | 有符号整数（1个字节）     |
|np.int16 | 有符号整数（2个字节）     |
|np.int32 | 有符号整数（4个字节）     |
|np.int64 | 有符号整数（8个字节）     |
|np.uint8 | 无符号整数（1个字节）     |
|np.uint16 | 无符号整数（2个字节）     |
|np.uint32 | 无符号整数（4个字节）     |
|np.uint64 | 无符号整数（8个字节）     |
|np.float16 | 半精度浮点数（2个字节）    |
|np.float32 | 单精度浮点数（4个字节）    |
|np.float64 | 双精度浮点数（8个字节）    |

| NDARRAY常用属性      | 描述              |
|------------------|-----------------|
| ndarray.ndim     | 秩，即轴的数量或维度的数量   |
| ndarray.shape    | 数组的形状           |
| ndarray.size     | 数组中数据的总个数       |
| ndarray.dtype    | 数组中的数据类型        |
| ndarray.itemsize | 数组中的数据大小，以字节为单位 |
| ndarray.nbytes   | 数组总内存占用量:size*itemsize。 |
| ndarray.flags    | 是否连续存储(高级优化) |

In [2]:
num = 789
arr = np.array(num)
print(num)
print(arr)
print(type(num))
print(type(arr))
print(arr.dtype)
print(arr.itemsize)
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.nbytes)
print('*' * 30)
print(arr.flags)

789
789
<class 'int'>
<class 'numpy.ndarray'>
int32
4
0
1
()
4
******************************
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [3]:
array = np.array([1, 2, 3.5, 6, 7, 8, 9])
print(array)
array = np.array([1, 2, 3.5, 6, 7, 8, 9], dtype=str)
print(array)
print(type(array))
print(len(array))
print(list(array))
print(tuple(array))
print(array[1::2])

[1.  2.  3.5 6.  7.  8.  9. ]
['1' '2' '3.5' '6' '7' '8' '9']
<class 'numpy.ndarray'>
7
['1', '2', '3.5', '6', '7', '8', '9']
('1', '2', '3.5', '6', '7', '8', '9')
['2' '6' '8']


In [4]:
lst = [1, 2, 3.5, 6, 7, 8, 9]
lst[1:4] = [99, 22]
print(lst)
# array[1:4] = [99, 22]
array[1:4] = [99, 22, 44]
print(array)

[1, 99, 22, 7, 8, 9]
['1' '99' '22' '44' '7' '8' '9']


In [5]:
print(lst)
print(arr)
print(arr.dtype)
print(arr.itemsize)
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.nbytes)
print('*' * 30)
print(arr.flags)

[1, 99, 22, 7, 8, 9]
789
int32
4
0
1
()
4
******************************
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [6]:
arr = np.array(lst, dtype=int)
print(arr.dtype)
print(arr.itemsize)
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.nbytes)
print('*' * 30)
print(arr.flags)

int32
4
1
6
(6,)
24
******************************
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [7]:
arr = np.array({'name': 'jake', 'age': 23})
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.itemsize)
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.nbytes)
print('*' * 30)
print(arr.flags)

{'name': 'jake', 'age': 23}
<class 'numpy.ndarray'>
object
8
0
1
()
8
******************************
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



![ndarray创建](picture/ndarray创建.png)

In [8]:
# lst = [[8, 9, 2], [3, 7]]
lst = [[8, 9, 2],
       [3, 7.2, 6]]
arr = np.array(lst)
print(lst)
print(arr)
print(len(lst))
print(len(arr))
print(arr.size)
print(arr.shape)
print(arr.nbytes)
print('*' * 30)
print(arr.flags)

[[8, 9, 2], [3, 7.2, 6]]
[[8.  9.  2. ]
 [3.  7.2 6. ]]
2
2
6
(2, 3)
48
******************************
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [9]:
zeros = np.zeros((2, 3), dtype=int)
print(zeros)

ones = np.ones((2, 3), dtype=int)
print(ones)

empty = np.empty((2, 2), dtype=int)
print(empty)

full = np.full((2, 4), 2025)
print(full)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[ 1304483492  1855204705]
 [ -341475263 -1514982963]]
[[2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [10]:
arr1 = np.zeros_like(zeros)
print(arr1)

arr1 = np.ones_like(ones)
print(arr1)

empty1 = np.empty_like(empty)
print(empty1)

full1 = np.full_like(full, 2026)
print(full1)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[ 1304483492  1855204705]
 [ -341475263 -1514982963]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [11]:
lst = [[[8, 9],
        [2, 3],
        [3, 7],
        [6, 8]]]
arr = np.array(lst)
print(arr)
print(arr.shape)

[[[8 9]
  [2 3]
  [3 7]
  [6 8]]]
(1, 4, 2)


In [12]:
lst = [[[[8, 9, 6],
         [2, 3, 0]],
        [[7, 6, 7],
         [4, 1, 3]]]]
arr = np.array(lst)
print(arr)
print(arr.shape)

[[[[8 9 6]
   [2 3 0]]

  [[7 6 7]
   [4 1 3]]]]
(1, 2, 2, 3)


In [13]:
lst = [[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],
       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]]
arr = np.array(lst)
print(arr.shape)

(2, 1, 4, 3)


#### np.arange([start,] stop[, step])
- 返回给定区间内的均匀间隔值构成的数组

In [14]:
print(list(range(1, 10, 2)))
print(np.arange(1, 10, 2))

[1, 3, 5, 7, 9]
[1 3 5 7 9]


In [15]:
print(list(range(9, 0, -2)))
print(np.arange(9, 0, -2))

[9, 7, 5, 3, 1]
[9 7 5 3 1]


In [16]:
print(list(range(1, 6)))
print(np.arange(1, 6))
print(list(range(6)))
print(np.arange(6))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [17]:
# print(list(range(1.5, 12, 2.5)))
print(np.arange(1.5, 12, 2.5))

[ 1.5  4.   6.5  9.  11.5]


#### np.linspace(start, stop, num=50, dtype=None)
- num：生成的样本数量  
- dtype：默认自动推断数据类型，推断出的 dtype 永远不会是整数；即使参数会产生一个整数数组，也会选择 np.float64
- 把给定区间分成 num 个均匀间隔的样本，构成数组并返回

In [18]:
print(np.linspace(1, 50))
print(np.linspace(1, 10, num=10))
print(np.linspace(1, 10, num=10, dtype=np.int32))
print(np.linspace(1, 10, num=10, dtype=int))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
print(np.linspace(1, 50, num=25))
print(np.linspace(1, 50, num=25, dtype=int))

[ 1.          3.04166667  5.08333333  7.125       9.16666667 11.20833333
 13.25       15.29166667 17.33333333 19.375      21.41666667 23.45833333
 25.5        27.54166667 29.58333333 31.625      33.66666667 35.70833333
 37.75       39.79166667 41.83333333 43.875      45.91666667 47.95833333
 50.        ]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 50]


#### 对数间隔数列 logspace
- np.logspace(start, stop, num=50, base=10)
- 返回指定指数范围、元素个数、底数的等比数列

In [20]:
arr = np.logspace(0, 4, 3, base=2)
print(arr)

arr = np.linspace(0, 4, 3)
print(arr)

arr = np.logspace(0, 4, 3)
print(arr)

[ 1.  4. 16.]
[0. 2. 4.]
[1.e+00 1.e+02 1.e+04]


#### 常用操作

#### np.reshape(arr_like, newshape)
- 保证 size 不变，在不更改数据的情况下为数组赋予新的形状
- newshape如果是整数，则结果将是该长度的1-D数组
- newshape的一个形状维度可以是-1，值将自行推断

In [21]:
arr = np.arange(24)
print(arr.reshape(4, 6))
print('*' * 30)
print(np.reshape(arr, (4, 6)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
******************************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [22]:
print(np.reshape(arr, (4, 2, 3)))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [23]:
arr = np.arange(24)
print(np.reshape(arr, (4, -1)))
# ValueError: cannot reshape array of size 24 into shape (5,newaxis)
# print(np.reshape(arr, (5, -1)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [24]:
arr = np.arange(24).reshape(4, 6)
print(np.reshape(arr, (24,)))
print(np.reshape(arr, 24))
print(np.reshape(arr, -1))
print(arr.reshape(24))
print(arr.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


#### ndarray.flatten()
- 返回扁平化到一维的数组

In [25]:
arr = np.arange(24).reshape(4, 6)
print(arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
