In [1]:
import numpy as np

#### 数组的算术运算和比较运算为逐元素操作

In [2]:
arr = np.arange(24).reshape(2, 3, 4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [3]:
print(arr > 10)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [4]:
print(arr + 10)

[[[10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]]

 [[22 23 24 25]
  [26 27 28 29]
  [30 31 32 33]]]


In [5]:
arr1 = np.arange(24).reshape(2, 3, 4)
arr2 = np.arange(30, 54).reshape(2, 3, 4)
print(arr1)
print('*' * 30)
print(arr2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
******************************
[[[30 31 32 33]
  [34 35 36 37]
  [38 39 40 41]]

 [[42 43 44 45]
  [46 47 48 49]
  [50 51 52 53]]]


In [6]:
print(arr1 + arr2)

[[[30 32 34 36]
  [38 40 42 44]
  [46 48 50 52]]

 [[54 56 58 60]
  [62 64 66 68]
  [70 72 74 76]]]


#### 后缘维度相同或者不同的维度有1，可以广播

In [7]:
arr1 = np.arange(48).reshape(2, 3, 2, 4)
arr2 = np.arange(50, 58).reshape(2, 4)
print(arr1)
print('*' * 30)
print(arr2)

[[[[ 0  1  2  3]
   [ 4  5  6  7]]

  [[ 8  9 10 11]
   [12 13 14 15]]

  [[16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]]

  [[32 33 34 35]
   [36 37 38 39]]

  [[40 41 42 43]
   [44 45 46 47]]]]
******************************
[[50 51 52 53]
 [54 55 56 57]]


In [8]:
print(arr1 + arr2)

[[[[ 50  52  54  56]
   [ 58  60  62  64]]

  [[ 58  60  62  64]
   [ 66  68  70  72]]

  [[ 66  68  70  72]
   [ 74  76  78  80]]]


 [[[ 74  76  78  80]
   [ 82  84  86  88]]

  [[ 82  84  86  88]
   [ 90  92  94  96]]

  [[ 90  92  94  96]
   [ 98 100 102 104]]]]


In [9]:
arr1 = np.arange(24).reshape(3, 2, 1, 4)
arr2 = np.arange(50, 62).reshape(1, 3, 4)
print(arr1)
print('*' * 30)
print(arr2)

[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]]


 [[[ 8  9 10 11]]

  [[12 13 14 15]]]


 [[[16 17 18 19]]

  [[20 21 22 23]]]]
******************************
[[[50 51 52 53]
  [54 55 56 57]
  [58 59 60 61]]]


In [10]:
print(arr1 + arr2)

[[[[50 52 54 56]
   [54 56 58 60]
   [58 60 62 64]]

  [[54 56 58 60]
   [58 60 62 64]
   [62 64 66 68]]]


 [[[58 60 62 64]
   [62 64 66 68]
   [66 68 70 72]]

  [[62 64 66 68]
   [66 68 70 72]
   [70 72 74 76]]]


 [[[66 68 70 72]
   [70 72 74 76]
   [74 76 78 80]]

  [[70 72 74 76]
   [74 76 78 80]
   [78 80 82 84]]]]


In [11]:
# [[[[ 0  1  2  3]
#    [ 0  1  2  3]
#    [ 0  1  2  3]]
#   [[ 4  5  6  7]
#    [ 4  5  6  7]
#    [ 4  5  6  7]]]
#  [[[ 8  9 10 11]
#    [ 8  9 10 11]
#    [ 8  9 10 11]]
#   [[12 13 14 15]
#    [12 13 14 15]
#    [12 13 14 15]]]
#  [[[16 17 18 19]
#    [16 17 18 19]
#    [16 17 18 19]]
#   [[20 21 22 23]
#    [20 21 22 23]
#    [20 21 22 23]]]]
# 
# 
# [[[[50 51 52 53]
#    [54 55 56 57]
#    [58 59 60 61]]
#   [[50 51 52 53]
#    [54 55 56 57]
#    [58 59 60 61]]]
#  [[[50 51 52 53]
#    [54 55 56 57]
#    [58 59 60 61]]
#   [[50 51 52 53]
#    [54 55 56 57]
#    [58 59 60 61]]]
#  [[[50 51 52 53]
#    [54 55 56 57]
#    [58 59 60 61]]
#   [[50 51 52 53]
#    [54 55 56 57]
#    [58 59 60 61]]]]


#### 数组除了支持Python序列的索引和切片操作以外，还可以针对各个轴进行索引和切片操作。

#### 序列索引和切片

In [12]:
lst = [8, 9, 2, 3, 7, 6]
arr = np.array(lst)
lst[1:4] = [100, 200]
# arr[1:4] = [100, 200]
# arr[1:4] = [100]
arr[1:4] = 100
print(lst)
print(arr)
arr[1:4] = [200, 300, 400]
print(arr)

[8, 100, 200, 7, 6]
[  8 100 100 100   7   6]
[  8 200 300 400   7   6]


In [13]:
lst = [6, 8, 9, 1, 3]
arr = np.array(lst)

print(lst)
item_lst = lst[2]
part_lst = lst[2:3] # 返回视图
print(item_lst)
print(part_lst)
print('*' * 30)

lst[2] = 99
print(lst)
print(item_lst)
print(part_lst)
print('*' * 30)

print(arr)
item_arr = arr[2]
part_arr = arr[2:3]
print(item_arr)
print(part_arr)
print('*' * 30)

arr[2] = 99
print(arr)
print(item_arr)
print(part_arr) # 动态性

[6, 8, 9, 1, 3]
9
[9]
******************************
[6, 8, 99, 1, 3]
9
[9]
******************************
[6 8 9 1 3]
9
[9]
******************************
[ 6  8 99  1  3]
9
[99]


#### 数组针对各个轴的索引和切片

In [14]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
lst_1 = lst[::2][1:]
print(lst_1)
arr_1 = arr[::2][1:]
print(arr_1)

print(arr[:, 1])

[[[7, 7, 1], [9, 1, 2]]]
[[[7 7 1]
  [9 1 2]]]
[[1 2 9]
 [3 6 2]
 [9 1 2]
 [3 4 6]]


In [15]:
lst[2] = [[2, 2, 2], [3, 3, 3]]
print(lst_1)
print(lst[::2][1:])
print('*' * 30)
arr[2] = [[2, 2, 2], [3, 3, 3]]
print(arr_1)
print(arr[::2][1:])

[[[7, 7, 1], [9, 1, 2]]]
[[[2, 2, 2], [3, 3, 3]]]
******************************
[[[2 2 2]
  [3 3 3]]]
[[[2 2 2]
  [3 3 3]]]


In [16]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
print(arr.shape)
print(arr[1])
print('*' * 30)
print(arr[1, 0])
print('*' * 30)
print(arr[1, 0, 2])
print(arr[1][0][2])
print(arr[1:2, :1, 2:])

(4, 2, 3)
[[6 7 4]
 [3 6 2]]
******************************
[6 7 4]
******************************
4
4
[[[4]]]


In [17]:
print(arr[::2, 1:])
print(arr[::2][1:])

[[[1 2 9]]

 [[9 1 2]]]
[[[7 7 1]
  [9 1 2]]]


In [18]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
print(arr.shape)
print(arr[1:, 0, ::-2])
print(arr[1:, 1, ::-2])

(4, 2, 3)
[[4 6]
 [1 7]
 [5 5]]
[[2 3]
 [2 9]
 [6 3]]


In [19]:
print(arr[::2, 1:])

[[[1 2 9]]

 [[9 1 2]]]


#### 数组的高阶索引
- 把整数列表或者bool数组作为索引

In [20]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
# 可以理解为 arr[3, 0, 2], arr[1, 1, 0],构成一个更高维度的数组
print(arr[[3, 1], [0, 1], [2, 0]])
print('*' * 30)
# 可以理解为 arr[3, 1], arr[1, 1], arr[2, 0]构成一个更高维度的数组
print(arr[[3, 1, 2], [1, 1, 0]])

[5 3]
******************************
[[3 4 6]
 [3 6 2]
 [7 7 1]]


In [21]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)

print(arr[[2, 1, 3, 0], [0, 1, 1, 0]])

[[7 7 1]
 [3 6 2]
 [3 4 6]
 [5 0 8]]


In [22]:
print(arr[[1, 1, 2]])
print(arr[1, 1, 2])

[[[6 7 4]
  [3 6 2]]

 [[6 7 4]
  [3 6 2]]

 [[7 7 1]
  [9 1 2]]]
2


In [23]:
print(arr[[1, 2]])

[[[6 7 4]
  [3 6 2]]

 [[7 7 1]
  [9 1 2]]]


In [24]:
print(arr[[1]])

[[[6 7 4]
  [3 6 2]]]


In [25]:
print(arr[1])

[[6 7 4]
 [3 6 2]]


In [26]:
a = np.array([1, 2, 3])
b = np.array([[1], [3], [2]])
print(a + b)

[[2 3 4]
 [4 5 6]
 [3 4 5]]


#### 基本索引和高阶索引组合时, 会发生广播

In [27]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
print(arr.shape)
print(arr[[2], [1], [2]])
print('*' * 30)
# shape (2,) () (2,) => (2,) (2,) (2,)
print(arr[[1, 3], 1, [2, 0]])
print(arr[[1, 3], [1], [2, 0]])
print(arr[[1, 3], [1, 1], [2, 0]])
print(arr[1, 1, [2, 0, 1]])

(4, 2, 3)
[2]
******************************
[2 3]
[2 3]
[2 3]
[2 3 6]


In [28]:
# shape (1,) () (3,) => (3,) (3,) (3,)
print(arr[[2], 1, [2, 0, 1]])
print(arr[[2, 2, 2], [1, 1, 1], [2, 0, 1]])

[2 9 1]
[2 9 1]


In [29]:
print(arr[1::2, 0, ::2])
print('*' * 30)
print(arr[1::2, 0:1, ::2])

[[6 4]
 [5 5]]
******************************
[[[6 4]]

 [[5 5]]]


#### 如果需要利用bool索引对标量进行操作, 也就是针对最后一个维度,只需要创建一个shape为(4, 2, 3)的bool索引即可

In [30]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
lst = [[[False, False, True],
        [False, False, False]],
       [[False, True, False],
        [False, False, False]],
       [[False, True, True],
        [False, False, False]],
       [[False, False, False],
        [True, False, False]]]
bool_arr = np.array(lst)
print(arr[bool_arr])

[8 7 7 1 3]


In [31]:
lst = [[False,
        True],
       [True,
        True],
       [False,
        False],
       [True,
        False]]
bool_arr = np.array(lst)
print(arr[bool_arr])

[[1 2 9]
 [6 7 4]
 [3 6 2]
 [5 1 5]]


In [32]:
lst = [True,
       False,
       True,
       True]
bool_arr = np.array(lst)
print(arr[bool_arr])
print('*' * 30)
print(arr[[0, 2, 3]])

[[[5 0 8]
  [1 2 9]]

 [[7 7 1]
  [9 1 2]]

 [[5 1 5]
  [3 4 6]]]
******************************
[[[5 0 8]
  [1 2 9]]

 [[7 7 1]
  [9 1 2]]

 [[5 1 5]
  [3 4 6]]]
