In [1]:
import numpy as np

#### 切片在高阶索引一侧, 按照轴的顺序定shape即可

In [2]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
print(arr.shape)
print(arr[1:, 0, [2, 1]])

(4, 2, 3)
[[4 7]
 [1 7]
 [5 1]]


In [3]:
print(arr[1:, [0, 1], [2, 1]])

[[4 6]
 [1 1]
 [5 4]]


In [4]:
print(arr[[2, 3, 1], [1, 0, 1], ::2])

[[9 2]
 [5 5]
 [3 2]]


#### 切片两侧都有高阶索引时, 定shape时高阶索引在前, 切片在后

In [5]:
print(arr[[3, 2], 1:, [1, 0]])

[[4]
 [9]]


![常用函数](picture/常用函数.png)

#### ... 简化不变操作

In [6]:
arr = np.arange(140 * 48 * 9).reshape(5, 7, 4, 6, 8, 9)
print(arr[::2, :, :, :, :, 8].shape)
print(arr[::2, ..., 8].shape)
print(arr[..., ::2, 1, 2].shape)

(3, 7, 4, 6, 8)
(3, 7, 4, 6, 8)
(5, 7, 4, 3)


#### ndarray.T
- 转置数组

In [7]:
a = np.arange(6).reshape(2, 3)
print(a)
print(a.T)
print('*' * 30)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
******************************


#### np.transpose(arr_like, axes=None)
- 通过axes参数排列数组的shape，axes没有指定，默认为转置

In [8]:
arr = np.arange(120).reshape(2, 3, 4, 5)
print(arr.T.shape)

print(np.transpose(arr).shape)
print(np.transpose(arr, (3, 2, 1, 0)).shape)

(5, 4, 3, 2)
(5, 4, 3, 2)
(5, 4, 3, 2)


#### np.swapaxes(arr_like, axis1, axis2)
- 交换数组的两个轴

In [9]:
print(np.swapaxes(arr, 1, -1).shape)

print(np.transpose(arr, (0, 3, 2, 1)).shape)

(2, 5, 4, 3)
(2, 5, 4, 3)


In [10]:
arr = np.arange(24).reshape(2, 3, 4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [11]:
print(arr.T)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [12]:
print(np.transpose(arr, (2, 0, 1)))

[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


#### np.concatenate(arrays, axis=0)
- arrays：Sequence[ArrayLike]
- 沿现有轴连接一系列数组，如果axis为None，则数组在使用前会被扁平化

In [13]:
a = np.arange(24).reshape(2, 3, 4)
b = np.arange(36).reshape(3, 3, 4)
print(np.concatenate((a, b), axis=None))
print(np.concatenate((a.flatten(), b.flatten()), axis=0))
print(np.concatenate((np.arange(24), np.arange(36)), axis=0))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [14]:
a = np.arange(24).reshape(3, 2, 4)
b = np.arange(36).reshape(3, 3, 4)
print(np.concatenate((a, b), axis=1))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 8  9 10 11]
  [12 13 14 15]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [15]:
a = np.arange(30).reshape(3, 2, 5)
b = np.arange(24).reshape(3, 2, 4)
print(np.concatenate((a, b), axis=2))

[[[ 0  1  2  3  4  0  1  2  3]
  [ 5  6  7  8  9  4  5  6  7]]

 [[10 11 12 13 14  8  9 10 11]
  [15 16 17 18 19 12 13 14 15]]

 [[20 21 22 23 24 16 17 18 19]
  [25 26 27 28 29 20 21 22 23]]]


In [16]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b.T), axis=1))
print(np.concatenate((a, b), axis=None))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


#### np.stack(arrays, axis=0)
- arrays：Sequence[ArrayLike]
- 沿新轴连接一系列数组

In [17]:
a1 = np.arange(6).reshape((2, 3))
a2 = np.arange(10, 16).reshape((2, 3))
a3 = np.arange(20, 26).reshape((2, 3))
a4 = np.arange(30, 36).reshape((2, 3))
print(np.stack((a1, a2, a3, a4)).shape)
print(np.stack((a1, a2, a3, a4)))

(4, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]

 [[30 31 32]
  [33 34 35]]]


In [18]:
print(np.stack((a1, a2, a3, a4), axis=1).shape)
print(np.stack((a1, a2, a3, a4), axis=1))

(2, 4, 3)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]
  [30 31 32]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]
  [33 34 35]]]


In [19]:
print(np.stack((a1, a2, a3, a4), axis=2).shape)
print(np.stack((a1, a2, a3, a4), axis=2))

(2, 3, 4)
[[[ 0 10 20 30]
  [ 1 11 21 31]
  [ 2 12 22 32]]

 [[ 3 13 23 33]
  [ 4 14 24 34]
  [ 5 15 25 35]]]


#### np.dot(a, b)
- 两个数组的点积

In [20]:
a = [3, 2, 0]
b = [1, 4, 9]
print(np.dot(a, b))

11


#### np.matmul(x1, x2)
- @操作符也可表示
- 两个数组的矩阵乘积


In [21]:
a = [[1, 2, 1],
     [3, 1, 2]]
b = [[1, 2, 1, 3],
     [2, 3, 0, 2],
     [0, 1, 3, 2]]
print(np.dot(a, b))
print(np.matmul(a, b))

[[ 5  9  4  9]
 [ 5 11  9 15]]
[[ 5  9  4  9]
 [ 5 11  9 15]]


In [22]:
arr1 = np.arange(30 * 63).reshape(5, 3, 2, 9, 7)
arr2 = np.arange(24 * 56).reshape(4, 6, 7, 8)
print(np.dot(arr1, arr2).shape)

(5, 3, 2, 9, 4, 6, 8)


In [23]:
arr2 = np.arange(24 * 72).reshape(4, 6, 9, 8)
arr1 = np.arange(30 * 56).reshape(5, 3, 2, 8, 7)
print(np.dot(arr2, arr1).shape)

(4, 6, 9, 5, 3, 2, 7)


In [24]:
arr1 = np.arange(15 * 63).reshape(5, 3, 1, 9, 7)
arr2 = np.arange(56).reshape(7, 8)
print(np.matmul(arr1, arr2).shape)
print((arr1 @ arr2).shape)

(5, 3, 1, 9, 8)
(5, 3, 1, 9, 8)


In [25]:
# 支持广播
arr2 = np.arange(6 * 56).reshape(6, 7, 8)
print(np.matmul(arr1, arr2).shape)
arr2 = np.arange(18 * 56).reshape(3, 6, 7, 8)
print(np.matmul(arr1, arr2).shape)

(5, 3, 6, 9, 8)
(5, 3, 6, 9, 8)


#### np.greater(x1, x2)
- x1，x2的形状必须相同，或者可以广播
- 按元素判断 x1 > x2 的结果

In [26]:
lst1 = [5, 1, 9]
lst2 = [[4, 3, 6],
        [7, 1, 5]]

print(np.greater(lst1, lst2))
print(np.array(lst1) > np.array(lst2))

[[ True False  True]
 [False False  True]]
[[ True False  True]
 [False False  True]]


#### np.greater_equal(x1, x2)
- x1，x2的形状必须相同，或者可以广播
- 按元素判断 x1 >= x2 的结果

In [27]:
print(np.greater_equal(lst1, lst2))
print(np.array(lst1) >= np.array(lst2))

[[ True False  True]
 [False  True  True]]
[[ True False  True]
 [False  True  True]]


#### np.less(x1, x2)
- x1，x2的形状必须相同，或者可以广播
- 按元素判断 x1 < x2 的结果

In [28]:
print(np.less(lst1, lst2))
print(np.array(lst1) < np.array(lst2))

[[False  True False]
 [ True False False]]
[[False  True False]
 [ True False False]]


#### np.less_equal(x1, x2)
- x1，x2的形状必须相同，或者可以广播
- 按元素判断 x1 <= x2 的结果

In [29]:
print(np.less_equal(lst1, lst2))
print(np.array(lst1) < np.array(lst2))

[[False  True False]
 [ True  True False]]
[[False  True False]
 [ True False False]]


#### np.equal(x1, x2)
- x1，x2的形状必须相同，或者可以广播
- 按元素判断 x1 == x2 的结果

In [30]:
print(np.equal(lst1, lst2))
print(np.array(lst1) == np.array(lst2))

[[False False False]
 [False  True False]]
[[False False False]
 [False  True False]]


#### np.not_equal(x1, x2)
- x1，x2的形状必须相同，或者可以广播
- 按元素判断 x1 != x2 的结果

In [31]:
print(np.not_equal(lst1, lst2))
print(np.array(lst1) != np.array(lst2))

[[ True  True  True]
 [ True False  True]]
[[ True  True  True]
 [ True False  True]]


#### np.sin(x)
- x：角度（弧度值）
- 正弦函数

In [32]:
import math

print(math.sin(math.pi / 6))
print(np.sin(np.pi / 6))

0.49999999999999994
0.49999999999999994


In [33]:
lst = [[0.6, 1.2, 0.5],
       [6, 9, 3]]
lst2 = [0, 30, 90]
# print(math.sin(lst))
print(np.sin(lst))
print(np.sin(np.array(lst2) * np.pi / 180))

[[ 0.56464247  0.93203909  0.47942554]
 [-0.2794155   0.41211849  0.14112001]]
[0.  0.5 1. ]


#### np.cos(x)
- x：角度（弧度值）
- 余弦函数

In [34]:
print(np.cos(np.pi / 2))
print(np.cos(np.array((0, 60, 90)) * np.pi / 180))

6.123233995736766e-17
[1.000000e+00 5.000000e-01 6.123234e-17]


#### np.tan(x)
- x：角度（弧度值）
- 正切函数

In [35]:
print(np.tan(-np.pi))
print(np.tan(np.array((0, 180)) * np.pi / 180))

1.2246467991473532e-16
[ 0.0000000e+00 -1.2246468e-16]


#### np.arcsin(x)/math.asin(x)
- 反正弦函数

In [36]:
print(math.asin(1))
print(np.arcsin(1))
print(np.arcsin(np.array([0.5, -0.5])))

1.5707963267948966
1.5707963267948966
[ 0.52359878 -0.52359878]


#### np.arccos(x)/math.acos(x)
- 反余弦函数

In [37]:
print(math.acos(-1))
print(np.arccos(-1))
print(np.arccos(np.array([0.5, 1])))

3.141592653589793
3.141592653589793
[1.04719755 0.        ]


#### np.arctan(x)/math.atan(x)
- 反正切函数

In [38]:
print(math.atan(1))
print(np.arctan(1))
print(np.arctan(np.array([0, -1])))

0.7853981633974483
0.7853981633974483
[ 0.         -0.78539816]


#### np.floor(x)
- 返回 x 的底限

In [39]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.floor(a))

[-2. -2. -1.  0.  1.  1.  2.]


#### np.ceil(x)
- 返回 x 的上限

In [40]:
print(np.ceil(a))

[-1. -1. -0.  1.  2.  2.  2.]


#### np.exp(x)
- 计算 e 的 x 幂次方

In [41]:
# e的0次方、e的1次方、e的2次方
print(np.exp([0, 1, 2]))

[1.         2.71828183 7.3890561 ]


#### np.log(x)
- 计算 x 的自然对数

In [42]:
print(np.log([1, np.e, np.e ** 2]))

[0. 1. 2.]


#### np.log2(x)
- 计算 x 的以 2 为底的对数

In [43]:
x = np.array([1, 2, 2 ** 4])
print(np.log2(x))

[0. 1. 4.]


#### np.log10(x)
- 计算 x 的以 10 为底的对数

In [44]:
print(np.log10([1e-15, 1000]))

[-15.   3.]


#### np.max(arr_like, axis=None, keepdims=False)
- 返回沿给定轴的最大值，axis没有指定时，默认为None，表示返回所有元素的最大值

In [45]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
print(np.max(arr))
print(np.max(arr, keepdims=True))

9
[[[9]]]


In [46]:
print(arr.shape)
print(np.max(arr, axis=0))
print(np.max(arr, axis=0, keepdims=True))

(4, 2, 3)
[[7 7 8]
 [9 6 9]]
[[[7 7 8]
  [9 6 9]]]


In [47]:
print(np.max(arr, axis=1))
print(np.max(arr, axis=1, keepdims=True))

[[5 2 9]
 [6 7 4]
 [9 7 2]
 [5 4 6]]
[[[5 2 9]]

 [[6 7 4]]

 [[9 7 2]]

 [[5 4 6]]]


In [48]:
print(np.max(arr, axis=2))
print(np.max(arr, axis=2, keepdims=True))

[[8 9]
 [7 6]
 [7 9]
 [5 6]]
[[[8]
  [9]]

 [[7]
  [6]]

 [[7]
  [9]]

 [[5]
  [6]]]


#### np.min(arr_like, axis=None, keepdims=False)
- 返回沿给定轴的最小值，axis没有指定时，默认为None，表示返回所有元素的最小值

In [49]:
print(np.min(arr, axis=2))

[[0 1]
 [4 2]
 [1 1]
 [1 3]]


#### np.mean(arr_like, axis=None, keepdims=False)
- 返回沿给定轴的平均值，axis没有指定时，默认为None，表示返回所有元素的平均值

In [50]:
print(np.mean(arr, axis=2))

[[4.33333333 4.        ]
 [5.66666667 3.66666667]
 [5.         4.        ]
 [3.66666667 4.33333333]]


#### np.var(arr_like, axis=None, keepdims=False)
- 返回沿给定轴的方差，axis没有指定时，默认为None，表示返回所有元素的方差

In [51]:
lis = [[0, 1, 7, 3],
       [4, 9, 6, 2],
       [8, 5, 11, 10]]
arr1 = np.array(lis)
print(np.var(arr1))
print(np.var(arr1, axis=0))
print(np.var(arr1, axis=1))

11.916666666666666
[10.66666667 10.66666667  4.66666667 12.66666667]
[7.1875 6.6875 5.25  ]


#### np.std(arr_like, axis=None, keepdims=False)
- 返回沿给定轴的标准差，axis没有指定时，默认为None，表示返回所有元素的标准差

In [52]:
arr1 = np.array(lis)
print(np.std(arr1))
print(np.std(arr1, axis=0))
print(np.std(arr1, axis=1))

3.452052529534663
[3.26598632 3.26598632 2.1602469  3.55902608]
[2.68095132 2.58602011 2.29128785]


#### np.prod(arr_like, axis=None, keepdims=np._NoValue,initial=np._NoValue)
- 返回给定轴上数组元素的乘积
- 默认的axis=None将计算输入数组中所有元素的乘积

In [53]:
lst = [[[5, 0, 8],
        [1, 2, 9]],
       [[6, 7, 4],
        [3, 6, 2]],
       [[7, 7, 1],
        [9, 1, 2]],
       [[5, 1, 5],
        [3, 4, 6]]]
arr = np.array(lst)
print(np.prod(arr))
print(np.prod(arr, axis=2))
print(np.prod(arr, axis=2, initial=10))

0
[[  0  18]
 [168  36]
 [ 49  18]
 [ 25  72]]
[[   0  180]
 [1680  360]
 [ 490  180]
 [ 250  720]]


#### np.sum(arr_like, axis=None, keepdims=np._NoValue,initial=np._NoValue)
- 返回给定轴上数组元素的和
- 默认的axis=None将计算输入数组中所有元素的和

In [54]:
print(np.sum(arr))
print(np.sum(arr, axis=2))
print(np.sum(arr, axis=2, initial=10))

104
[[13 12]
 [17 11]
 [15 12]
 [11 13]]
[[23 22]
 [27 21]
 [25 22]
 [21 23]]


#### 中位数 median

In [55]:
print(np.median(arr))
print(np.median(arr, axis=0))
print(np.median(arr, axis=2))
# print(np.median(arr, axis=2, initial=10))

4.5
[[5.5 4.  4.5]
 [3.  3.  4. ]]
[[5. 2.]
 [6. 3.]
 [7. 2.]
 [5. 4.]]


#### np.argmax(arr_like, axis=None)
- 返回沿轴的最大值的索引
- 没有指定轴，则数组扁平化处理

In [56]:
print(arr.flatten())
# 没有指定轴，则数组扁平化处理
print(np.argmax(arr))
print(np.argmax(arr, axis=0))

[5 0 8 1 2 9 6 7 4 3 6 2 7 7 1 9 1 2 5 1 5 3 4 6]
5
[[2 1 0]
 [2 1 0]]


In [57]:
print(np.argmax(arr, axis=1))

[[0 1 1]
 [0 0 0]
 [1 0 1]
 [0 1 1]]


#### np.argmin(arr_like, axis=None)
- 返回沿轴的最小值的索引
- 没有指定轴，则数组扁平化处理

In [58]:
print(np.argmin(arr))
print(np.argmin(arr, axis=0))

1
[[0 0 2]
 [0 2 1]]


#### np.maximum(x1, x2)
- 返回x1和x2逐个元素比较中的最大值

In [59]:
lst1 = [5, 1, 9]
lst2 = [[4, 3, 6],
        [7, 1, 5]]
print(np.greater(lst1, lst2))
print(np.maximum(lst1, lst2))

[[ True False  True]
 [False False  True]]
[[5 3 9]
 [7 1 9]]


#### np.minimum(x1, x2)
- 返回x1和x2逐个元素比较中的最小值

In [60]:
print(np.minimum(lst1, lst2))

[[4 1 6]
 [5 1 5]]
