In [1]:
import numpy as np

#### np.nonzero(arr_like)
返回非零元素的索引

In [2]:
lst = [[[0, 0, 8],
        [0, 0, 0]],
       [[0, 0, 0],
        [3, 0, 0]],
       [[0, 6, 1],
        [0, 0, 0]],
       [[9, 0, 0],
        [0, 0, 0]]]
arr = np.array(lst)
'''
8: 0 0 2
3: 1 1 0
6: 2 0 1
1: 2 0 2
9: 3 0 0
'''
print(np.nonzero(arr))
print([np.nonzero(arr)])
print(arr[np.nonzero(arr)])

(array([0, 1, 2, 2, 3], dtype=int64), array([0, 1, 0, 0, 0], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))
[(array([0, 1, 2, 2, 3], dtype=int64), array([0, 1, 0, 0, 0], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))]
[8 3 6 1 9]


In [3]:
print(arr > 5)
print(np.nonzero(arr > 5))
print(arr[np.nonzero(arr > 5)])

[[[False False  True]
  [False False False]]

 [[False False False]
  [False False False]]

 [[False  True False]
  [False False False]]

 [[ True False False]
  [False False False]]]
(array([0, 2, 3], dtype=int64), array([0, 0, 0], dtype=int64), array([2, 1, 0], dtype=int64))
[8 6 9]


#### np.where(condition, x=None, y=None)
- condition : array_like, bool
- x, y：array_like，要么都传参，要么都不传
- 如果传三个参数，条件成立返回x，不成立时返回y
- 如果只传第一个参数，返回符合条件的元素的索引

In [4]:
print(arr != 0)
print(np.where(arr != 0))

[[[False False  True]
  [False False False]]

 [[False False False]
  [ True False False]]

 [[False  True  True]
  [False False False]]

 [[ True False False]
  [False False False]]]
(array([0, 1, 2, 2, 3], dtype=int64), array([0, 1, 0, 0, 0], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))


#### 如果只传第一个参数，返回符合条件的元素的索引

In [5]:
print(arr[np.nonzero(arr)])
print(arr[np.where(arr != 0)])
print(arr[np.nonzero(arr > 5)])
print(arr[np.where(arr > 5)])

[8 3 6 1 9]
[8 3 6 1 9]
[8 6 9]
[8 6 9]


#### 当where内有三个参数时，当condition成立时返回x，当condition不成立时返回y

In [6]:
# shape:(2,3)
cond = [[False, True, False],
        [True, False, False]]
# shape:(3,)->(2,3)
x = [1, 2, 3]
# shape:(1,3)->(2,3)
y = [[4, 5, 6]]
print(np.where(cond, x, y))

[[4 2 6]
 [1 5 6]]


#### np.argwhere(arr_like)
- 找出数组中按元素分组的非零元素的索引

In [7]:
lst = [[[0, 0, 8],
        [0, 0, 0]],
       [[0, 0, 0],
        [3, 0, 0]],
       [[0, 6, 1],
        [0, 0, 0]],
       [[9, 0, 0],
        [0, 0, 0]]]
arr = np.array(lst)
print(arr[np.nonzero(arr)])
print(np.argwhere(arr))

[8 3 6 1 9]
[[0 0 2]
 [1 1 0]
 [2 0 1]
 [2 0 2]
 [3 0 0]]


#### np.random.normal(loc=0.0, scale=1.0, size=None)
- 返回从正态分布中抽取的随机样本
- 正态分布又称为常态分布或高斯分布，通常记作X~N（μ ,σ**2）。其中， μ是正态分布的数学期望（均值）， σ2是正态分布的方差。μ = 0,σ = 1的正态分布被称为标准正态分布
- loc：均值（中心）
- scale：标准差
- size：输出的形状

In [8]:
print(np.random.normal())
print(np.random.normal(size=(2, 3, 4)))

0.46435633997413456
[[[-0.29262623  0.80931901  2.4216276   0.25861917]
  [ 0.41869048  0.29925261  0.02754457  1.12876554]
  [ 2.00615782 -0.56786643  0.94562059  1.80614375]]

 [[-0.20598207 -1.15196765  0.62913892  0.42138022]
  [ 0.73049544  0.23853829 -0.62796446  0.34013007]
  [-0.36841677 -0.23650255 -1.58981404  0.01565933]]]


In [9]:
print(np.random.normal(loc=10))
(np.random.normal(loc=10, size=(2, 3, 4)))

11.654656775144336


array([[[10.28778258,  8.67586551,  8.75710456, 10.6132955 ],
        [11.0497511 ,  9.62757483,  9.70867096,  8.87126866],
        [10.88117821,  9.42049331, 10.34058341, 10.69357546]],

       [[ 9.70972667, 10.29309822, 10.15814618,  9.86000973],
        [11.4226868 ,  8.95536224,  8.34109606,  9.04998653],
        [11.50500632,  9.89312844,  9.40442131,  8.91489392]]])

In [10]:
print(np.random.normal(loc=10, scale=5))
(np.random.normal(loc=10, scale=5, size=(2, 3, 4)))

4.210924934955905


array([[[ 8.93188961, 16.14083933,  7.68484845, 10.39143035],
        [ 3.0223155 ,  3.72177095,  4.80378005, 11.89726191],
        [14.13823655, 11.62019867, 16.0718401 , 12.81752974]],

       [[ 7.62407196, 14.65906691,  9.44980386,  9.20015848],
        [ 9.50698078, 15.66505386,  7.36724888,  9.32015421],
        [ 9.55086698,  5.47428666,  1.80377305, 10.20595475]]])

#### np.random.randint(low, high=None, size=None)
- 返回从 [low, high) 离散均匀分布中抽取的随机整数

In [11]:
print(np.random.randint(2))
print(np.random.randint(2, size=5))  # 等价于下一行
print(np.random.randint(0, 2, size=5))  # 等价于上一行
print(np.random.randint(2, 8, size=(2, 3)))

0
[1 1 1 0 1]
[1 1 0 0 0]
[[6 6 6]
 [6 2 3]]


#### np.random.uniform(low=0.0, high=1.0, size=None)
- 返回从 [low, high) 均匀分布中抽取的随机样本

In [12]:
print(np.random.uniform(8))
print(np.random.uniform(3.5, size=5))  # 等价于下一行
print(np.random.uniform(0, 3.5, size=5))  # 等价于上一行
print(np.random.uniform(2.5, 3.5, size=(2, 3, 4)))

3.707785437129065
[3.316323   1.97930546 2.89938286 1.9376353  3.18782238]
[1.79722985 0.85444892 2.32854112 3.15778992 1.42704749]
[[[2.66246931 3.30772883 2.6687212  2.53595331]
  [2.64257948 2.64700035 3.05881421 3.25389563]
  [2.62014189 2.79294314 3.38082217 3.36015656]]

 [[2.73595866 2.5209162  3.28256338 2.70836873]
  [2.92093555 3.26177882 3.39110548 3.30427558]
  [2.62466075 2.64663123 3.18611999 3.10459178]]]


#### np.random.permutation(x)
- x：int or array_like
- 如果 x 是整数，返回随机排列的 np.arange(x)
- 如果 x 是数组，只对数组的第一个维度随机排列，返回新的数组

In [13]:
print(np.arange(9))
# 等价于返回一个随机排列的np.arange(9)
print(np.random.permutation(9))

[0 1 2 3 4 5 6 7 8]
[3 6 0 4 5 8 2 7 1]


In [14]:
arr = np.arange(24).reshape(4, 2, 3)
print(arr)
print('*' * 30)
print(np.random.permutation(arr))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
******************************
[[[18 19 20]
  [21 22 23]]

 [[ 0  1  2]
  [ 3  4  5]]

 [[12 13 14]
  [15 16 17]]

 [[ 6  7  8]
  [ 9 10 11]]]


#### np.random.seed([x])
- 随机数种子

In [15]:
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))
np.random.seed(5)
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))

[[28]
 [28]]
3.123335435912136
[[23]
 [14]]
3.283104400783315
[[79]
 [62]]
1.9134383106788528


In [16]:
np.random.seed(5)
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))

[[79]
 [62]]
1.9134383106788528


In [17]:
np.random.seed(3)
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))

[[25]
 [ 4]]
2.081809477825889


In [18]:
# 恢复随机
np.random.seed()
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))

[[63]
 [ 3]]
1.8118207672289157
