In [1]:
import numpy as np

#### np.nonzero(arr_like)
返回非零元素的索引

In [2]:
lst = [[[0, 0, 8],
        [0, 0, 0]],
       [[0, 0, 0],
        [3, 0, 0]],
       [[0, 6, 1],
        [0, 0, 0]],
       [[9, 0, 0],
        [0, 0, 0]]]
arr = np.array(lst)
'''
8: 0 0 2
3: 1 1 0
6: 2 0 1
1: 2 0 2
9: 3 0 0
'''
print(np.nonzero(arr))
print([np.nonzero(arr)])
print(arr[np.nonzero(arr)])

(array([0, 1, 2, 2, 3], dtype=int64), array([0, 1, 0, 0, 0], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))
[(array([0, 1, 2, 2, 3], dtype=int64), array([0, 1, 0, 0, 0], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))]
[8 3 6 1 9]


In [3]:
print(arr > 5)
print(np.nonzero(arr > 5))
print(arr[np.nonzero(arr > 5)])

[[[False False  True]
  [False False False]]

 [[False False False]
  [False False False]]

 [[False  True False]
  [False False False]]

 [[ True False False]
  [False False False]]]
(array([0, 2, 3], dtype=int64), array([0, 0, 0], dtype=int64), array([2, 1, 0], dtype=int64))
[8 6 9]


#### np.where(condition, x=None, y=None)
- condition : array_like, bool
- x, y：array_like，要么都传参，要么都不传
- 如果传三个参数，条件成立返回x，不成立时返回y
- 如果只传第一个参数，返回符合条件的元素的索引

In [4]:
print(arr != 0)
print(np.where(arr != 0))

[[[False False  True]
  [False False False]]

 [[False False False]
  [ True False False]]

 [[False  True  True]
  [False False False]]

 [[ True False False]
  [False False False]]]
(array([0, 1, 2, 2, 3], dtype=int64), array([0, 1, 0, 0, 0], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))


#### 如果只传第一个参数，返回符合条件的元素的索引

In [5]:
print(arr[np.nonzero(arr)])
print(arr[np.where(arr != 0)])
print(arr[np.nonzero(arr > 5)])
print(arr[np.where(arr > 5)])

[8 3 6 1 9]
[8 3 6 1 9]
[8 6 9]
[8 6 9]


#### 当where内有三个参数时，当condition成立时返回x，当condition不成立时返回y

In [6]:
# shape:(2,3)
cond = [[False, True, False],
        [True, False, False]]
# shape:(3,)->(2,3)
x = [1, 2, 3]
# shape:(1,3)->(2,3)
y = [[4, 5, 6]]
print(np.where(cond, x, y))

[[4 2 6]
 [1 5 6]]


#### np.argwhere(arr_like)
- 找出数组中按元素分组的非零元素的索引

In [7]:
lst = [[[0, 0, 8],
        [0, 0, 0]],
       [[0, 0, 0],
        [3, 0, 0]],
       [[0, 6, 1],
        [0, 0, 0]],
       [[9, 0, 0],
        [0, 0, 0]]]
arr = np.array(lst)
print(arr[np.nonzero(arr)])
print(np.argwhere(arr))

[8 3 6 1 9]
[[0 0 2]
 [1 1 0]
 [2 0 1]
 [2 0 2]
 [3 0 0]]


#### np.random.normal(loc=0.0, scale=1.0, size=None)
- 返回从正态分布中抽取的随机样本
- 正态分布又称为常态分布或高斯分布，通常记作X~N（μ ,σ**2）。其中， μ是正态分布的数学期望（均值）， σ2是正态分布的方差。μ = 0,σ = 1的正态分布被称为标准正态分布
- loc：均值（中心）
- scale：标准差
- size：输出的形状

In [8]:
print(np.random.normal())
print(np.random.normal(size=(2, 3, 4)))

-0.6315469743757247
[[[ 0.33691639 -0.12944963  0.69316645  0.26896045]
  [-0.79340633  0.34270995 -1.00498169  0.82137274]
  [ 0.8678683   0.14729821 -1.14972019 -0.61892186]]

 [[-0.09874971  0.04506453  0.23882207 -0.99680086]
  [-1.37039561  2.78596201  0.84452074  1.04508687]
  [-0.65158602  2.15317954 -0.97918572 -0.92928483]]]


In [9]:
print(np.random.normal(loc=10))
np.random.normal(loc=10, size=(2, 3, 4))

9.786694974408624


array([[[10.0270316 ,  9.74471195, 10.49934665, 12.19782783],
        [11.40760134,  8.5690297 , 11.32107388,  8.96287804],
        [ 8.88727234,  9.26271988,  8.78327798,  9.67304195]],

       [[ 9.25420714, 10.49353822, 11.87428683, 11.40771836],
        [10.35023081,  9.2375818 , 11.7630568 , 11.34694459],
        [10.0167724 ,  9.46524735,  8.62184711, 10.74770503]]])

In [10]:
print(np.random.normal(loc=10, scale=5))
np.random.normal(loc=10, scale=5, size=(2, 3, 4))

6.126261451834811


array([[[ 8.84483311, 10.33521478, 13.88851771,  7.55783327],
        [ 7.71704199,  3.97445254, 11.36232317,  1.5099799 ],
        [10.97474589,  9.27539053, 11.97209183,  8.4197371 ]],

       [[ 8.53659939,  6.08424181,  2.82042706,  3.13179027],
        [ 8.95871886,  8.59481293, 10.88762751, 22.24662936],
        [12.56467439,  9.8699122 ,  4.70373814,  8.15547957]]])

#### np.random.randint(low, high=None, size=None)
- 返回从 [low, high) 离散均匀分布中抽取的随机整数

In [11]:
print(np.random.randint(2))
print(np.random.randint(2, size=5))  # 等价于下一行
print(np.random.randint(0, 2, size=5))  # 等价于上一行
print(np.random.randint(2, 8, size=(2, 3)))

1
[0 1 1 1 1]
[1 0 0 1 0]
[[2 7 3]
 [4 2 7]]


#### np.random.uniform(low=0.0, high=1.0, size=None)
- 返回从 [low, high) 均匀分布中抽取的随机样本

In [12]:
print(np.random.uniform(8))
print(np.random.uniform(3.5, size=5))  # 等价于下一行
print(np.random.uniform(0, 3.5, size=5))  # 等价于上一行
print(np.random.uniform(2.5, 3.5, size=(2, 3, 4)))

3.2960750580544786
[3.21462142 1.08296119 2.04422945 1.58809574 3.07737908]
[3.04693102 3.12080193 2.10679251 3.40153341 1.56255333]
[[[2.75554912 3.45621875 2.74898556 2.90951633]
  [3.15800811 3.10563236 3.14746634 2.97194838]
  [3.2478956  2.52553423 2.95886959 2.51161829]]

 [[3.28055285 3.32686783 3.29102511 2.71309541]
  [3.34331577 3.2867165  2.78604552 3.0361627 ]
  [3.0735291  3.29508487 3.03396005 2.82961741]]]


#### np.random.permutation(x)
- x：int or array_like
- 如果 x 是整数，返回随机排列的 np.arange(x)
- 如果 x 是数组，只对数组的第一个维度随机排列，返回新的数组

In [13]:
print(np.arange(9))
# 等价于返回一个随机排列的np.arange(9)
print(np.random.permutation(9))

[0 1 2 3 4 5 6 7 8]
[1 6 5 7 3 0 2 8 4]


In [14]:
arr = np.arange(24).reshape(4, 2, 3)
print(arr)
print('*' * 30)
print(np.random.permutation(arr))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
******************************
[[[18 19 20]
  [21 22 23]]

 [[12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


#### np.random.seed([x])
- 随机数种子

In [15]:
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))
np.random.seed(5)
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))

[[27]
 [60]]
2.646653600610829
[[72]
 [18]]
2.504323600943334
[[79]
 [62]]
1.9134383106788528


In [16]:
np.random.seed(5)
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))

[[79]
 [62]]
1.9134383106788528


In [17]:
np.random.seed(3)
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))

[[25]
 [ 4]]
2.081809477825889


In [18]:
# 恢复随机
np.random.seed()
print(np.random.randint(1, 90, size=(2, 1)))
print(np.random.uniform(1.5, 3.5))

[[81]
 [84]]
2.5183290726597463
